[workspace]
members = [
    "argentum-core",
]

[package]
name = "argentum-gb"
version = "0.1.0"
authors = ["Anish Jewalikar <anishjewalikar@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
argentum-core = { path = "./argentum-core" }
bytemuck = "1.5.1"
clap = "3.0.0-beta.2"
glow = "0.8.1"
glutin = "0.26.0"
