[package]
name = "argentum-web"
version = "0.4.2"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
argentum = { path = "../argentum" }
js-sys = "0.3.52"
rodio = { version = "0.14.0", default-features = false, features = ["wasm-bindgen"] }
wasm-bindgen = "0.2.76"
