[package]
name = "argentum-native"
version = "0.4.2"
authors = ["Anish Jewalikar <anishjewalikar@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
argentum = { path = "../argentum" }
clap = "3.0.0-beta.4"
fermium = "20014.4.2"
